image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl
      
      # Install Terraform
      sudo wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install -y terraform
      
      # Install AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf aws awscliv2.zip
      
      # Install kubectl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/
      
      mkdir -p terraform
    command: |
      echo "Environment ready!"

vscode:
  extensions:
    - hashicorp.terraform
    - amazonwebservices.aws-toolkit-vscode
    - ms-kubernetes-tools.vscode-kubernetes-tools
